[package]
name = "bake"
version = "0.1.0"
authors = ["Emily A. Bellows <emily.a.bellows@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
clap = {version = "3.0.0-beta.1", git = "https://github.com/clap-rs/clap/" }
png = "0.16.4"
libflate = "1.0.1"
